// SPDX-FileCopyrightText: 2026 ReallyMe LLC
//
// SPDX-License-Identifier: MIT OR Apache-2.0

import type { ReallyMeWasmProvider } from "./wasmProvider.js";
import {
  processOperationResponse,
  processOperationResponseJson,
  aes128GcmSeal,
  aes128GcmOpen,
  aes192GcmSeal,
  aes192GcmOpen,
  aes256GcmSeal,
  aes256GcmOpen,
  aes256GcmSivSeal,
  aes256GcmSivOpen,
  chacha20Poly1305Seal,
  chacha20Poly1305Open,
  xchacha20Poly1305Seal,
  xchacha20Poly1305Open,
  aes128KwWrapKey,
  aes128KwUnwrapKey,
  aes192KwWrapKey,
  aes192KwUnwrapKey,
  aes256KwWrapKey,
  aes256KwUnwrapKey,
  argon2idDeriveKey,
  kmac256Derive,
  hpkeSealBase,
  hpkeOpenBase,
  mlDsa44GenerateKeypair,
  mlDsa44DeriveKeypair,
  mlDsa44Sign,
  mlDsa44Verify,
  mlDsa65GenerateKeypair,
  mlDsa65DeriveKeypair,
  mlDsa65Sign,
  mlDsa65Verify,
  mlDsa87GenerateKeypair,
  mlDsa87DeriveKeypair,
  mlDsa87Sign,
  mlDsa87Verify,
  mlKem512GenerateKeypair,
  mlKem512DeriveKeypair,
  mlKem512Encapsulate,
  mlKem512Decapsulate,
  mlKem768GenerateKeypair,
  mlKem768DeriveKeypair,
  mlKem768Encapsulate,
  mlKem768Decapsulate,
  mlKem1024GenerateKeypair,
  mlKem1024DeriveKeypair,
  mlKem1024Encapsulate,
  mlKem1024Decapsulate,
  slhDsaSha2128sGenerateKeypair,
  slhDsaSha2128sDeriveKeypair,
  slhDsaSha2128sSign,
  slhDsaSha2128sVerify,
  rsaVerifyPkcs1v15,
  rsaVerifyPss,
  xWing768GenerateKeypair,
  xWing768DeriveKeypair,
  xWing768Encapsulate,
  xWing768Decapsulate,
} from "../dist/wasm/reallyme_crypto_wasm.js";

export const bundledWasmFunctions = Object.freeze({
  processOperationResponse,
  processOperationResponseJson,
  aes128GcmSeal,
  aes128GcmOpen,
  aes192GcmSeal,
  aes192GcmOpen,
  aes256GcmSeal,
  aes256GcmOpen,
  aes256GcmSivSeal,
  aes256GcmSivOpen,
  chacha20Poly1305Seal,
  chacha20Poly1305Open,
  xchacha20Poly1305Seal,
  xchacha20Poly1305Open,
  aes128KwWrapKey,
  aes128KwUnwrapKey,
  aes192KwWrapKey,
  aes192KwUnwrapKey,
  aes256KwWrapKey,
  aes256KwUnwrapKey,
  argon2idDeriveKey,
  kmac256Derive,
  hpkeSealBase,
  hpkeOpenBase,
  mlDsa44GenerateKeypair,
  mlDsa44DeriveKeypair,
  mlDsa44Sign,
  mlDsa44Verify,
  mlDsa65GenerateKeypair,
  mlDsa65DeriveKeypair,
  mlDsa65Sign,
  mlDsa65Verify,
  mlDsa87GenerateKeypair,
  mlDsa87DeriveKeypair,
  mlDsa87Sign,
  mlDsa87Verify,
  mlKem512GenerateKeypair,
  mlKem512DeriveKeypair,
  mlKem512Encapsulate,
  mlKem512Decapsulate,
  mlKem768GenerateKeypair,
  mlKem768DeriveKeypair,
  mlKem768Encapsulate,
  mlKem768Decapsulate,
  mlKem1024GenerateKeypair,
  mlKem1024DeriveKeypair,
  mlKem1024Encapsulate,
  mlKem1024Decapsulate,
  slhDsaSha2128sGenerateKeypair,
  slhDsaSha2128sDeriveKeypair,
  slhDsaSha2128sSign,
  slhDsaSha2128sVerify,
  rsaVerifyPkcs1v15,
  rsaVerifyPss,
  xWing768GenerateKeypair,
  xWing768DeriveKeypair,
  xWing768Encapsulate,
  xWing768Decapsulate,
}) satisfies Readonly<Record<keyof ReallyMeWasmProvider, unknown>>;

/** Reject any replacement of the package-owned WASM callables before global installation. */
export const verifyBundledWasmModule = (module: object): boolean => {
  try {
    for (const [name, expected] of Object.entries(bundledWasmFunctions)) {
      const descriptor = Object.getOwnPropertyDescriptor(module, name);
      const candidate = descriptor?.get === undefined ? descriptor?.value : Reflect.get(module, name);
      if (candidate !== expected) {
        return false;
      }
    }
  } catch {
    return false;
  }
  return true;
};
